# FROM node:24-slim
FROM node:24-alpine

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

ARG NEXT_PUBLIC_ACCTIVITY_API_URL
ARG NEXT_PUBLIC_LOCATION_API_URL
ENV NEXT_PUBLIC_ACCTIVITY_API_URL=$NEXT_PUBLIC_ACCTIVITY_API_URL
ENV NEXT_PUBLIC_LOCATION_API_URL=$NEXT_PUBLIC_LOCATION_API_URL

RUN printenv
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]